### ISSUE TITLE
require('internal-ip').v4.sync() returns null

### ISSUE THREAD

**Issue by fohrloop** [sindresorhus/internal-ip#17]
Hi,

First of all, thanks for this awesome package. It has been working many months flawlessly, even on my machine, where many other packages seem to produce consistently or randomly wrong ip-addresses.

Today I upgraded to v.3.0.1.

On my PC (Windows 10), `require('internal-ip').v4.sync()` returns always null. I am not an expert on JS, but what I can see from putting a console.log into the` internal-ip\index.js`:

```
function sync(family) {
	try {
		const result = defaultGateway[family].sync();
		return findIp(result.gateway) || null;
	} catch (err) {
        console.log(err) <----- logging
		return null;
	}
}
```

is this:
```
TypeError: (gwTable || "").trim is not a function
    at parse (C:\MyProject\src\client\node_modules\default-gateway\win32.js:12:19)
    at sync (C:\MyProject\src\client\node_modules\default-gateway\win32.js:56:10)
    at Function.module.exports.v4.sync (C:\MyProject\src\client\node_modules\default-gateway\win32.js:62:32)
    at Function.module.exports.v4.sync (C:\MyProject\src\client\node_modules\default-gateway\index.js:17:46)
    at sync (C:\MyProject\src\client\node_modules\internal-ip\index.js:36:41)
    at Function.module.exports.v4.sync (C:\MyProject\src\client\node_modules\internal-ip\index.js:48:32)
    at Object.<anonymous> (C:\MyProject\src\client\server.js:8:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

the version of `default-gateway` is 2.6.1. Is this a problem of default-gateway or interal-ip? I should also mention, that the "Promise version" (`require('internal-ip').v4()`) _does_ work correctly.

**Update:**
Downgraded to `internal-ip v.1.2.0` and it works fine; just using it as `var ip = require('internal-ip')()`.

**Comment by silverwind** [comment]
Fixed in https://github.com/silverwind/default-gateway/commit/7cd19afd92723621dcebf12e1fb21faa2e50a180. It was a bug only affecting sync methods on Windows. I'm sorry it slipped. If you reinstall the module, it should now work for you.

**Comment by fohrloop** [comment]
Thanks!
